import { integer, jsonb, pgTable, serial, text, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

// A single behavioral event captured from the storefront. Kept intentionally
// generic (type + freeform payload) so we don't need a schema migration
// every time we want to track a new kind of interaction.
export const EVENT_TYPES = [
  "page_view",
  "product_view",
  "add_to_cart",
  "remove_from_cart",
  "wishlist_add",
  "wishlist_remove",
  "search",
  "checkout_started",
  "purchase_completed",
] as const;

export type EventType = (typeof EVENT_TYPES)[number];

export const eventsTable = pgTable("events", {
  id: serial("id").primaryKey(),
  // Anonymous per-browser id (stored in localStorage client-side) so we can
  // recognize returning visitors without requiring login.
  visitorId: text("visitor_id").notNull(),
  type: text("type").notNull(), // one of EVENT_TYPES
  // Freeform details specific to the event type, e.g. { productId, slug,
  // name, price } for product_view, or { query } for search.
  payload: jsonb("payload").$type<Record<string, unknown>>().notNull().default({}),
  path: text("path"), // page URL the event happened on
  referrer: text("referrer"), // document.referrer at time of event, for traffic source
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const insertEventSchema = createInsertSchema(eventsTable).omit({
  id: true,
  createdAt: true,
});
export type InsertEvent = z.infer<typeof insertEventSchema>;
export type Event = typeof eventsTable.$inferSelect;

// Rule-based customer segment, computed from event history. Recomputed
// on demand (see routes/segments.ts) rather than continuously, since the
// catalog and traffic are small enough that real-time isn't needed yet.
export const CUSTOMER_SEGMENTS = [
  "window_shopper",
  "interested_buyer",
  "high_intent_buyer",
  "returning_customer",
  "vip_customer",
] as const;

export type CustomerSegment = (typeof CUSTOMER_SEGMENTS)[number];

export const customerSegmentsTable = pgTable("customer_segments", {
  id: serial("id").primaryKey(),
  visitorId: text("visitor_id").notNull().unique(),
  email: text("email"), // filled in once we see them at checkout
  segment: text("segment").notNull(),
  // Short, human-readable rationale for the segment — generated by
  // DeepSeek from the visitor's event summary, e.g. "Viewed the Shadow
  // Jacket 6 times and added it to cart twice without purchasing."
  insight: text("insight"),
  eventCount: integer("event_count").notNull().default(0),
  purchaseCount: integer("purchase_count").notNull().default(0),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const insertCustomerSegmentSchema = createInsertSchema(customerSegmentsTable).omit({
  id: true,
  updatedAt: true,
});
export type InsertCustomerSegment = z.infer<typeof insertCustomerSegmentSchema>;
export type CustomerSegmentRow = typeof customerSegmentsTable.$inferSelect;
